
---

version: '3.8'
services:
  spc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    networks:
    - spc-net
    volumes:
      - my-vol:/docs/data
    environment:
    - TEST=hello
networks:
  spc-net:
    driver: bridge 
volumes:
  my-vol:
    driver: local
    
---

version: '3.8'
services:
  my-nginx:
    image: nginx:latest
    ports:
    - 80:80  

  
---

version: '3.8'
services:
  nop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nop
    ports:
      - 32000:5000
    networks:
      - nopnet 
  nopdb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=nop123
      - MYSQL_USER=nop
      - MYSQL_PASSWORD=nop123
      - MYSQL_DATABASE=nop
    container_name: nopdb
    ports:
      - 3306
    volumes:
      - "nop-db:/var/lib/mysql"
    networks:
      - nopnet

networks:
  public:
  private:
  nopnet:
volumes:
  nop-db:
---

    

