---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-labels1
  labels:
    app: nginx
    env: dev
    release: v1.1
spec:
  containers:
  - name: webserver
    image: nginx:1.25
    ports:
    - containerPort: 80
      protocol: TCP



